### ISSUE TITLE
[help] How to import shadcn components in dark mode?

### ISSUE THREAD

**Issue by belugawhale3** [vercel/nextjs-subscription-payments#316]
I'm trying to import shadcn components such as the button:
https://ui.shadcn.com/docs/components/button
However because the button I'm importing from shadcn is black its completely disappears in the black background from the SAAS starter. Is there a way to import it in this repo so that it uses the shadcn dark mode theme instead and is visible?
Also whats the best way to go about importing shadcn components to this repo?

**Comment by fluid-design-io** [comment]
@belugawhale3 Since Shadcn uses [`theme tokens`](https://ui.shadcn.com/docs/theming) to style components, you can simple **overwrite** the style.css `@layer base :root` to the dark mode theme, for example:
Default css
```css
@layer base {
  :root {
// ...light theme
}
.dark {
// ...dark theme
}
}
```

You can then replace what's in the root with the values from the `.dark {...}` like so:

```css
@layer base {
  :root {
// ...dark theme
}
}
```

That's it :)
