### ISSUE TITLE
getUserDetails returns first subscription result but not the actual user of subscription

### ISSUE THREAD

**Issue by hype08** [vercel/nextjs-subscription-payments#50]
inside of UserContext.js, getUserDetails selects a single record,  just the first one.
`  const getUserDetails = () => supabase.from('users').select('*').single();`

this will work for the first user but for the subsequent signups, the /account page will show the subscription for the first signup user. also, when clicking the customer portal to manage the account, it will not work.

**Comment by thorwebdev** [comment]
@hype08 Supabase employs Postgres policies, e.g. for the users table, a user can only read their own record (see https://github.com/vercel/nextjs-subscription-payments/blob/main/schema.sql#L16)

Therefore `supabase.from('users').select('*').single()` will only return a single record, namely the user details of the currently authenticated user. If there were more than one record `.single()` would actually return an error.

If you're getting an error, then you might be using the secret `service_role` key instead of the public `anon` key.

**Comment by hype08** [comment]
thank you for your reply @thorwebdev !

you're right.. i did double check the db policy in supabase, and made sure the policy was as you had mentioned..

when i have more than one account in the db, the account page for the second user still shows the plan for the first user 🤔

is the service role key absolutely unnecessary in the vercel environment variables setting?

**Comment by hype08** [comment]
right now i have 
- STRIPE_WEBHOOK_SECRET_LIVE
- STRIPE_SECRET_KEY_LIVE
- NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY_LIVE
- NEXT_PUBLIC_SUPABASE_ANON_KEY
- SUPABASE_SERVICE_ROLE_KEY
- NEXT_PUBLIC_SUPABASE_URL

as production environment variables inside of vercel.. 

thank you for your help!

**Comment by hype08** [comment]
@thorwebdev i figured it out! it was user error. thanks for pointing me in the right direction! 
i changed the policy of the subscription table for testing supabase. after switching it back to private, worked as intended. thank u again!
